#!/bin/bash

echo $2
case "$1" in
    compile)
        for f in `find $2 -name "*.elm" | grep -v "elm-stuff"`
        do
            base_file="${f%.*}"
            output_dir="${3:-output}"
            echo "Processing $f"
            mkdir -p "$output_dir"
            if [[ $* != *--unsafe* ]]
            then
                elm-make $f --output .tmp-elm.js
                rm .tmp-elm.js
            fi
            dir_suffix=${base_file#$2}
            dir_prefix=${2%$dir_suffix}

            echo "Copying to $output_dir$dir_suffix.ex"

            node elmchemy.js $f > $output_dir$dir_suffix.ex

            # do something on $f
        done
        ;;

    *)
        echo $"Usage: $0 compile [input_dir] [output_dir] [--unsafe]"
        exit 1

esac
