#!/bin/bash

function create_file {
    local file=$1
    if echo $file | grep elm-stuff/packages; then
        file=`sed sed "s/elm-stuff\/packages/deps/"`
    fi
    mkdir -p `dirname $file`
    echo "" > $file
    echo "$file"
}

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SOURCE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

case "$1" in
    init)
        if [ -a ./mix.exs ]
        then
            mix archive.install https://github.com/wende/elmchemy/releases/download/0.0.32/elmchemy-0.1.3.ez
            mkdir -p elm
            cp $SOURCE_DIR/templates/elm-package.json ./
            cp $SOURCE_DIR/templates/Hello.elm ./elm/
            cp $SOURCE_DIR/templates/elmchemy_test.exs ./test/
            printf  "Elmchemy initialised. Make sure to add:\n\n\tcompilers: [:elmchemy, :yecc, :leex, :erlang, :elixir, :app],\n\telmchemy_path: \"elm\",\n\nto your mix.exs file\nThen run mix test to check if everything went fine\n"

        else
            printf  "ERROR: No elixir project found. Make sure to run init in a project"
        fi
    ;;
    compile)
        rm -rf ".elmchemy"
        echo "" > .elmchemy_output
        for f in `{ find $2 -name "*.elm" | grep -v "elm-stuff" | grep -v "#." ; find $2../elm-stuff/packages -name "*.elm" ;}`
        do
            echo "----------"
            echo "Compiling $f"
            echo ">>>>$f" >> .elmchemy_output
            elm-package install -y
            elm-make $f --output .elmchemy_output_tmp.js || { echo 'Compilation failed' ; exit 1; }
            rm .elmchemy_output_tmp.js
            cat $f >> .elmchemy_output
        done
        node $SOURCE_DIR/elmchemy.js .elmchemy_output > .elmchemy_elixir_output
        current_file=""
        while IFS= read -r line; do
            if [[ $line =~ ">>>>" ]]; then
                current_file="${line/\/\///}"
                current_file="${current_file%%.*}.ex"
                current_file="${current_file/>>>>$2/$3}"
                echo "$current_file"
                current_file=$(create_file $current_file)
                else
                if [ "$current_file" != "" ]; then
                    printf '%s\n' "$line" >> "$current_file"
                fi
            fi
        done < .elmchemy_elixir_output

        ;;
    *)
        echo $"Usage: $0 compile [input_dir] [output_dir] [--unsafe]"
        exit 1

esac
